In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("volcanoes.txt")

In [9]:
df[:10]

,VOLCANX020,NUMBER,NAME,LOCATION,STATUS,ELEV,TYPE,TIMEFRAME,LAT,LON
0,509.0,1201-01=,Baker,US-Washington,Historical,3285.0,Stratovolcanoes,D3,48.776798,-121.810997
1,511.0,1201-02-,Glacier Peak,US-Washington,Tephrochronology,3213.0,Stratovolcano,D4,48.111801,-121.111000
2,513.0,1201-03-,Rainier,US-Washington,Dendrochronology,4392.0,Stratovolcano,D3,46.869801,-121.751000
3,515.0,1201-05-,St. Helens,US-Washington,Historical,2549.0,Stratovolcano,D1,46.199799,-122.181000
4,516.0,1201-04-,Adams,US-Washington,Tephrochronology,3742.0,Stratovolcano,D6,46.205799,-121.490997
5,517.0,1201-06-,West Crater,US-Washington,Radiocarbon,1329.0,Volcanic field,D7,45.879799,-122.081001
6,518.0,1201-07-,Indian Heaven,US-Washington,Radiocarbon,1806.0,Shield volcanoes,D7,45.929798,-121.820999
7,519.0,1202-01-,Hood,US-Oregon,Historical,3426.0,Stratovolcano,D3,45.373798,-121.691002
8,521.0,1202-02-,Jefferson,US-Oregon,Varve Count,3199.0,Stratovolcano,D6,44.691799,-121.801002
9,522.0,1202-03-,Blue Lake Crater,US-Oregon,Radiocarbon,1230.0,Maar,D7,44.419800,-121.771004

In [10]:
df["LON"]

0    -121.810997
1    -121.111000
2    -121.751000
3    -122.181000
4    -121.490997
5    -122.081001
6    -121.820999
7    -121.691002
8    -121.801002
9    -121.771004
10   -121.931000
11   -121.831001
12   -121.841003
13   -121.771004
14   -121.771004
15   -121.681000
16   -121.221001
17   -121.820999
18   -120.861000
19   -122.100998
20   -120.751000
21   -120.661003
22   -122.121002
23   -110.670998
24   -118.751000
25   -117.471001
26   -117.801002
27   -113.501000
28   -112.450996
29   -114.350998
         ...
32   -113.221001
33   -122.200996
34   -121.441002
35   -121.361000
36   -121.600998
37   -121.551002
38   -120.831001
39   -121.501000
40   -122.771004
41   -119.721001
42   -107.030998
43   -119.030998
44   -112.501000
45   -119.001000
46   -119.021004
47   -118.871002
48   -119.051002
49   -117.450996
50   -112.670998
51   -113.621002
52   -112.401001
53   -118.320999
54   -117.820999
55   -113.130997
56   -116.621002
57   -106.570999
58   -111.501000
59   -115.780998
60   -108.001000
61   -105.931000
Name: LON, Length: 62, dtype: float64